name: build

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
      - run: go build -o hi ./cmd/sitegen
      - run: ./hi render --input index.hi --out public/index.html --data-dir data --layout templates/layout.html
      - name: Commit and push if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add public/ data/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Daily build: update site and data" && git push)
